a = float(input("Digite o 1° Valor: "))
b = float(input("Digite o 2° Valor" ))
print("A soma é", (a+b))
print("A subtração é", (a-b))
print("A multiplicação é", (a*b))
print("A divisão é", (a/b))
print("O resto da divisão é", (a%b))
print("Parte inteira é", (a//b))
a = float(input("Digite sua Base L1: "))
b = float(input("Digite a altura L2: "))
print("a multiplicação das ")